"""Build the admin UI's self-contained CSS layer.

Emits two files into ``admin_service/static/``, both derived from the main
application so the two UIs can never drift apart:

* ``tokens.css``    - the main app's Material-3 tokens, verbatim, for the light
                      (``:root``) and dark (``.dark``) themes.
* ``tailwind.css``  - a Tailwind base reset plus the utility subset that the
                      admin markup actually uses: copied from the main app's
                      generated ``static/tailwind.css`` where it has them, built
                      here from the token names for colours, and hand-written
                      for the few remaining layout utilities.

The admin service must render without CDN access, mirroring the main UI which
also vendors its Tailwind build - hence the generated, dependency-free output.

Run after changing any class in ``index.html`` / ``app.js`` / ``styles.css``:

    python tools/gen_admin_tailwind.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ADMIN = ROOT / "admin_service" / "static"
SRC = ROOT / "static" / "tailwind.css"  # the main app's generated Tailwind build
MAIN_HTML = ROOT / "static" / "index.html"  # source of truth for the tokens
DST = ADMIN / "tailwind.css"
TOKENS_DST = ADMIN / "tokens.css"

TOKEN_PREFIX = "--c-"
TOKEN_RE = re.compile(rf"({re.escape(TOKEN_PREFIX)}[A-Za-z0-9-]+)\s*:\s*([^;]+);")

# Admin UI sources whose classes the utility layer has to cover.
SOURCES = ["index.html", "app.js", "docs.html", "docs.js"]

# --------------------------------------------------------------- token layer
def extract_theme_tokens(html: str, selector: str) -> list[tuple[str, str]]:
    """Return the ``(name, value)`` pairs declared by a standalone theme block.

    ``.dark`` also prefixes compound selectors (``.dark .style-btn``); only the
    standalone block declares tokens, so a match without ``--c-`` is skipped.
    """
    for match in re.finditer(re.escape(selector) + r"\s*\{", html):
        end = html.index("}", match.end())
        found = TOKEN_RE.findall(html[match.end() : end])
        if found:
            return found
    raise SystemExit(f"no {selector} token block found in {MAIN_HTML}")


main_html = MAIN_HTML.read_text(encoding="utf-8")
light_tokens = extract_theme_tokens(main_html, ":root")
dark_tokens = extract_theme_tokens(main_html, ".dark")

token_names = {name[len(TOKEN_PREFIX) :] for name, _ in light_tokens}
if token_names != {name[len(TOKEN_PREFIX) :] for name, _ in dark_tokens}:
    only_light = sorted(token_names - {n[len(TOKEN_PREFIX) :] for n, _ in dark_tokens})
    only_dark = sorted({n[len(TOKEN_PREFIX) :] for n, _ in dark_tokens} - token_names)
    raise SystemExit(f"theme token sets differ: light-only={only_light} dark-only={only_dark}")


def render_block(selector: str, tokens: list[tuple[str, str]]) -> str:
    body = "\n".join(f"  {name}: {value.strip()};" for name, value in tokens)
    return f"{selector} {{\n{body}\n}}"


TOKENS_FILE = "\n".join(
    [
        "/* Admin UI design tokens.",
        "   Generated by tools/gen_admin_tailwind.py - do not edit by hand.",
        f"   Extracted verbatim from the main application ({MAIN_HTML.name}), which is",
        "   the single source of truth for the palette: the yellow primary, the grey",
        "   surface ramp, and the two themes. Re-run the generator after changing a",
        "   token there; file_translator/tests/unit/test_admin_ui_tokens.py fails if",
        "   this file is left stale.",
        "*/",
        "",
        render_block(":root", light_tokens),
        "",
        render_block(".dark", dark_tokens),
        "",
    ]
)
TOKENS_DST.write_text(TOKENS_FILE, encoding="utf-8")

# ------------------------------------------------------- used-class harvesting
# Every markup/script file the admin UI ships - the documentation page included,
# so a class it uses is held to the same "must have a rule" standard.
sources = [(ADMIN / name).read_text(encoding="utf-8") for name in SOURCES]
custom_css = (ADMIN / "styles.css").read_text(encoding="utf-8")

tokens: set[str] = set()
for blob in sources:
    for match in re.finditer(r'class="([^"]*)"', blob):
        tokens.update(t for t in match.group(1).split() if t and "${" not in t and not t.startswith("js-"))

# Component classes live in styles.css; `dark` is a state hook, not a utility.
custom = set(re.findall(r"\.([A-Za-z][A-Za-z0-9_-]*)\s*[,{]", custom_css))
custom |= {"dark", "matrix", "role-select"}
wanted = {t for t in tokens if t not in custom}


def escape(name: str) -> str:
    """Escape a class name for use in a CSS selector."""
    return "".join(ch if (ch.isalnum() or ch in "-_") else "\\" + ch for ch in name)


# ------------------------------------------------- semantic token utilities
# `text-on-surface-variant` / `bg-primary` / `hover:border-outline` / ... so the
# markup never names a colour and a theme switch needs no markup change.
SEMANTIC_RE = re.compile(r"^(?:(hover|focus):)?(text|bg|border|accent)-(.+)$")
DECLARATION = {
    "text": "color: var({var})",
    "bg": "background-color: var({var})",
    "border": "border-color: var({var})",
    "accent": "accent-color: var({var})",
}


def semantic_rule(name: str) -> str | None:
    match = SEMANTIC_RE.match(name)
    if not match:
        return None
    state, prop, token = match.groups()
    if token not in token_names:
        return None
    selector = f".{escape(name)}"
    if state:
        selector += f":{state}"
    return f"{selector}{{{DECLARATION[prop].format(var=TOKEN_PREFIX + token)}}}"


semantic: dict[str, str] = {}
for name in sorted(wanted):
    rule = semantic_rule(name)
    if rule:
        semantic[name] = rule
        wanted.discard(name)

# --------------------------------------------------- copy from the main build
wanted_sel = {escape(t): t for t in wanted}
src = SRC.read_text(encoding="utf-8")

blocks: list[tuple[str, str, str]] = []
i, n = 0, len(src)
while i < n:
    brace = src.find("{", i)
    if brace == -1:
        break
    prelude = src[i:brace].strip()
    depth, j = 1, brace + 1
    while j < n and depth:
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
        j += 1
    blocks.append(("atrule" if prelude.startswith("@") else "rule", prelude, src[brace + 1 : j - 1]))
    i = j

plain: dict[str, list[str]] = {}
media: dict[str, dict[str, list[str]]] = {}
copied: set[str] = set(wanted_sel)

for kind, prelude, body in blocks:
    if kind == "atrule":
        continue
    for sel, decl in re.findall(r"([^{}]+)\{([^{}]*)\}", f"{prelude}{{{body}}}"):
        for one in (s.strip() for s in sel.strip().split(",")):
            if one.lstrip(".") not in wanted_sel:
                continue
            text = f"{one}{{{decl}}}"
            if prelude.startswith("@media"):
                media.setdefault(prelude, {}).setdefault(one, []).append(text)
            else:
                plain.setdefault(one, []).append(text)
            copied.discard(one.lstrip("."))

# ------------------------------------------------------- hand-written layers
# Layout utilities absent from the main app's build (Tailwind v3 defaults).
SUPPLEMENT = """
/* --- utilities absent from the main UI build (Tailwind v3 defaults) --- */
.flex-wrap { flex-wrap: wrap; }
.items-start { align-items: flex-start; }
.gap-1\\.5 { gap: 0.375rem; }
.mr-1 { margin-right: 0.25rem; }
.mt-2 { margin-top: 0.5rem; }
.mt-8 { margin-top: 2rem; }
.p-5 { padding: 1.25rem; }
.pb-6 { padding-bottom: 1.5rem; }
.py-1\\.5 { padding: 0.375rem 0.625rem; }
.w-60 { width: 15rem; }
.rounded-2xl { border-radius: 1rem; }
.max-h-\\[60vh\\] { max-height: 60vh; }
.border-r { border-right-width: 1px; }
.space-y-1 > * + * { margin-top: 0.25rem; }
.space-y-2 > * + * { margin-top: 0.5rem; }
.space-y-3 > * + * { margin-top: 0.75rem; }
.space-y-4 > * + * { margin-top: 1rem; }
.grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }

.tracking-wide { letter-spacing: 0.025em; }
.text-base { font-size: 1rem; line-height: 1.5rem; }
.text-3xl { font-size: 1.875rem; line-height: 2.25rem; }
.font-\\[Geist\\] { font-family: Geist, ui-sans-serif, system-ui, sans-serif; }
.font-\\[Space_Grotesk\\] { font-family: "Space Grotesk", ui-sans-serif, system-ui, sans-serif; }
.font-\\[JetBrains_Mono\\] { font-family: "JetBrains Mono", ui-monospace, SFMono-Regular, monospace; }

@media (min-width: 768px) {
  .md\\:flex { display: flex; }
  .md\\:grid-cols-4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }
}
@media (min-width: 1024px) {
  .lg\\:grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
"""

# Preflight-style base. Without it native controls keep the user-agent
# appearance - that is what made the navigation render as white blocks with
# invisible text (no reset shipped with the utility subset). Must stay ahead of
# the utilities; component display rules live in styles.css, after this file.
BASE = """
/* --- base reset (Tailwind preflight subset) --- */
*, ::before, ::after { box-sizing: border-box; }
body { margin: 0; line-height: 1.5; -webkit-font-smoothing: antialiased; }
h1, h2, h3, h4, h5, h6, p, figure, blockquote, dl, dd { margin: 0; }
ul, ol { margin: 0; padding: 0; list-style: none; }
table { border-collapse: collapse; border-spacing: 0; }
img, svg { display: block; max-width: 100%; }
button, input, select, textarea {
  font: inherit;
  color: inherit;
  background-color: transparent;
  border: 0;
  margin: 0;
}
button { cursor: pointer; }
button:disabled { cursor: not-allowed; }
input::placeholder, textarea::placeholder { color: var(--c-on-surface-variant); opacity: 1; }
"""

out: list[str] = [
    "/* Admin UI utility layer.",
    "   Generated by tools/gen_admin_tailwind.py - do not edit by hand.",
    "   Self-contained: the admin service must render without CDN access,",
    "   mirroring the main UI which also vendors its Tailwind build.",
    "   Colours come from tokens.css, which is generated from the main app. */",
    "",
    BASE.strip(),
    "",
    "/* --- semantic colour utilities, built from the design tokens --- */",
    *[semantic[name] for name in sorted(semantic)],
    "",
]
groups: dict[str, list[str]] = {}
for sels in plain.values():
    first = sels[0]
    body = first[first.index("{") + 1 : -1]
    groups.setdefault(body, []).append(first[: first.index("{")])
if groups:
    out.append("/* --- utilities copied from the main UI build --- */")
for body, sels in groups.items():
    out.append(",".join(sels) + "{" + body + "}")
out.append("")
for prelude, sels in media.items():
    out.append(f"{prelude}{{")
    for rules in sels.values():
        out.extend(rules)
    out.append("}")
    out.append("")
out.append(SUPPLEMENT.strip())
out.append("")

DST.write_text("\n".join(out), encoding="utf-8")

# ------------------------------------------------------------- self-check --
# A class counts as covered when a rule for it starts right after the escaped
# name; `>`, `+`, `~` count too, because child-combinator utilities
# (`.space-y-1 > * + *`) are legitimate rules.
final = DST.read_text(encoding="utf-8")
still = sorted(
    t
    for t in tokens - custom
    if not re.search(re.escape("." + escape(t)) + r"(?=\s*[,{+>~:])", final)
)
print(f"tokens: {len(light_tokens)} light / {len(dark_tokens)} dark -> tokens.css")
print(f"utilities used by the admin UI: {len(tokens - custom)}")
print(f"  semantic colour utilities:   {len(semantic)}")
print(f"  copied from the main build:  {len(copied)}")
print(f"  from the hand-written supplement: {len(wanted) - len(copied)}")
print(f"still missing after build:    {len(still)}  {' '.join(still)}")
print(f"size: {DST.stat().st_size} bytes (tailwind.css), {TOKENS_DST.stat().st_size} bytes (tokens.css)")
